[package]
name = "bevy-procedural-geometry"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.9.0" }
smooth-bevy-cameras = { version = "0.6.0", git = "https://github.com/bonsairobo/smooth-bevy-cameras/", rev = "1388352469519b1451cd85482c46c8a4252440e7" }